In [8]:
FILE_PATH = './Data_Files/class1.txt'
f = open(FILE_PATH,'r')
f

In [59]:
def openClass():
    while True:
        filename = input()
        FILE_PATH = './Data_Files/' + filename + '.txt'
        try:
            f = open(FILE_PATH,'r+')
        except Exception as e:
            print(e)
        else:
            print('\n SUCCESSFULLY OPENED\n', filename)
            f.close()
            break

In [60]:
openClass()

 class1

 SUCCESSFULLY OPENED
 class1

# Task 2

In [61]:
def analyzeClass():
    while True:
        filename = input()
        FILE_PATH = './Data_Files/' + filename + '.txt'
        try:
            f = open(FILE_PATH,'r+')
        except Exception as e:
            print(e)
        else:
            print('\n SUCCESSFULLY OPENED\n', filename)
          #  f.close()
          #  break
    
        print("**** ANALYZING ****")
    
        k = 0 # number of lines
        error = 0 # number of lines error
        
        for line in f.readlines():
            k += 1
            listValue = line.rstrip('\n').split(',')
            if(len(listValue) != 26):
                print('invalid line of data \n')
                print(line,'\n')
                error += 1
            elif not listValue[0][1:].isnumeric() or len(listValue[0]) != 9:
                print('Invalid line of data : N# is invalid \n')
                print(line, '\n')
                error += 1
        if error == 0:
            print('no error found!')
        
        print('\n**** Report ****\n')
        print('số dòng hợp lệ : ', k - error, '\n')
        print('số dòng bị lỗi:' , error)
        
        choice = input('bạn có muốn nhập thêm không? (0: không, 1: có)')
        if int(choice) == 0:
            break

In [62]:
analyzeClass()

 class1

 SUCCESSFULLY OPENED
 class1
**** ANALYZING ****
no error found!

**** Report ****

số dòng hợp lệ :  20

số dòng bị lỗi: 0

bạn có muốn nhập thêm không? (0: không, 1: có) 0

# Task 3

In [63]:
while True:
    filename = input()
    FILE_PATH = './Data_Files/' + filename + '.txt'
    try:
        f = open(FILE_PATH,'r+')
    except Exception as e:
        print(e)
    else:
        print('\n SUCCESSFULLY OPENED\n', filename)
      #  f.close()
      #  break

    print("**** ANALYZING ****")

    k = 0 # number of lines
    error = 0 # number of lines error
    grade = [] # list grade
    valid_line = []
    answer_key = 'B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D'.split(',')
    for line in f.readlines():
        k += 1
        listValue = line.rstrip('\n').split(',')
        if(len(listValue) != 26):
            print('invalid line of data \n')
            print(line,'\n')
            error += 1
        elif not listValue[0][1:].isnumeric() or len(listValue[0]) != 9:
            print('Invalid line of data : N# is invalid \n')
            print(line, '\n')
            error += 1
        else:
            valid_line.append(listValue)
    print(valid_line[1])
    for line in valid_line:
        answer = line[1:]
        score = 0
        for j in range(25):
            if answer[j] == answer_key[j] :
                score += 4
            elif answer[j] =='':
                score += 0
            else :
                score -= 1
        grade.append(score)

    if error == 0:
        print('no error found!')
        
    print('\n**** Report ****\n')
    print('số dòng hợp lệ : ', k - error, '\n')
    print('số dòng bị lỗi:' , error)
    print('Mean (average) score : ', sum(grade)/len(grade),'\n')
    print('Highest score : ', max(grade), '\n')
    print('Lowest score: ', min(grade), '\n')
    print('Range of scores: ', max(grade) - min(grade), '\n')
    s = sorted(grade)
    n = len(grade)
    if n % 2 == 0:
        median = (s[n//2 - 1] + s[n//2]) /2.0
    else:
        median = s[n//2]
    print('Median score: ', median, '\n')
    
    choice = input('bạn có muốn nhập thêm không? (0: không, 1: có)')
    if int(choice) == 0:
        break

 class1

 SUCCESSFULLY OPENED
 class1
**** ANALYZING ****
['N00000002', '', 'A', '', 'D', '', 'B', 'D', 'A', 'C', 'C', 'D', '', 'A', 'A', 'A', 'C', 'B', 'D', 'C', 'C', 'A', 'A', 'B', '', 'D']
no error found!

**** Report ****

số dòng hợp lệ :  20

số dòng bị lỗi: 0
Mean (average) score :  75.6

Highest score :  91

Lowest score:  59

Range of scores:  32

Median score:  73.0

bạn có muốn nhập thêm không? (0: không, 1: có) 0

# Task 4

In [66]:
while True:
    filename = input()
    FILE_PATH = './Data_Files/' + filename + '.txt'
    try:
        f = open(FILE_PATH,'r+')
    except Exception as e:
        print(e)
    else:
        print('\n SUCCESSFULLY OPENED\n', filename)
      #  f.close()
      #  break

    print("**** ANALYZING ****")

    student_number = []
    grade = [] # list grade
    valid_line = []
    answer_key = 'B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D'.split(',')
    for line in f.readlines():
        listValue = line.rstrip('\n').split(',')
        if len(listValue) == 26 and listValue[0][1:].isnumeric() and len(listValue[0]) == 9:
            valid_line.append(listValue)
            
    for line in valid_line:
        student_number.append(line[0])
        answer = line[1:]
        score = 0
        for j in range(25):
            if answer[j] == answer_key[j] :
                score += 4
            elif answer[j] =='':
                score += 0
            else :
                score -= 1
        grade.append(score)
    FILE_PATH_GRADE = './Data_Files/' + filename + '_grade.txt'
    with open(FILE_PATH_GRADE, 'w') as fw:
         for sn,gr in zip(student_number,grade):
             fw.write(sn + ',' + str(gr) + '\n')
         print('successfully write file ' + filename + "_grade.txt \n")
    f.close()
    
    choice = input('bạn có muốn nhập thêm không? (0: không, 1: có)')
    if int(choice) == 0:
        break

 class1

 SUCCESSFULLY OPENED
 class1
**** ANALYZING ****
successfully write file class1_grade.txt

bạn có muốn nhập thêm không? (0: không, 1: có) 1
 class2

 SUCCESSFULLY OPENED
 class2
**** ANALYZING ****
successfully write file class2_grade.txt

bạn có muốn nhập thêm không? (0: không, 1: có) 0

# Task 5

In [68]:
import numpy as np
import pandas as pd

In [67]:
for i in range(1,9):
    FILE_PATH_DATA = './Data_Files/class' + str(i) + '.txt'
    FILE_PATH_DATA_TASK_5 = './Data_Files/class' + str(i) + '_task5.txt'
    
    with open(FILE_PATH_DATA, 'r') as f:
        with open(FILE_PATH_DATA_TASK_5,'w') as fw:
            for line in f.readlines():
                listValue = line.rstrip('\n').split(',')
                if len(listValue) == 26 and listValue[0][1:].isnumeric() and len(listValue[0]) == 9:
                    fw.write(line)

In [70]:
while True:
    filename = input()
    FILE_PATH = './Data_Files/' + filename + '_task5.txt'
    try:
        df = pd.read_csv(FILE_PATH,delimiter = ',', header = None, index_col = 0 )
        df.index.name = "student_number"
        df = df.fillna(0) # fill giá trị rỗng = 0
    except Exception as e:
        print(e)
    else:
        print('\n SUCCESSFULLY OPENED\n', filename)
        break
df

 class1

 SUCCESSFULLY OPENED
 class1

,1,2,3,4,5,6,7,8,9,10,...,16,17,18,19,20,21,22,23,24,25
student_number,,,,,,,,,,,,,,,,,,,,,
N00000001,A,A,D,D,C,D,D,A,0,C,...,C,B,D,A,C,0,A,0,C,D
N00000002,0,A,0,D,0,B,D,A,C,C,...,C,B,D,C,C,A,A,B,0,D
N00000003,B,A,0,D,C,B,D,A,C,C,...,C,B,D,A,0,A,0,B,D,D
N00000004,B,B,D,0,0,B,D,A,C,C,...,C,B,D,0,C,A,D,B,C,D
N00000005,B,A,0,D,0,B,D,A,C,C,...,C,B,D,D,C,A,A,0,D,D
N00000006,B,A,D,A,C,B,D,A,C,C,...,C,0,C,A,C,A,C,B,D,A
N00000007,B,A,D,D,C,B,D,A,C,0,...,C,B,D,0,C,A,A,B,D,0
N00000008,A,A,D,D,C,0,D,A,C,C,...,A,B,D,A,C,A,0,B,B,D
N00000009,B,A,0,D,C,B,D,A,C,A,...,A,B,D,A,C,A,A,B,D,D
N00000010,0,A,D,B,C,B,D,A,C,C,...,C,B,D,A,D,0,0,B,D,B
N00000011,B,A,D,0,C,B,D,A,C,D,...,C,B,D,A,C,A,B,B,D,D
N00000012,B,0,D,D,C,B,D,A,C,C,...,A,B,D,A,0,A,A,A,0,C
N00000013,0,A,D,0,B,B,0,A,C,A,...,C,B,D,A,C,A,A,B,D,D
N00000014,B,B,D,D,C,B,0,D,C,C,...,C,0,D,A,C,A,A,0,D,D
N00000015,A,C,C,D,C,B,0,A,C,C,...,C,B,D,A,C,A,B,0,D,D
N00000016,B,A,C,D,0,B,D,A,C,C,...,C,B,D,A,C,A,A,B,D,D
N00000017,B,A,D,D,C,B,C,A,D,C,...,C,B,D,D,B,0,A,B,D,D
N00000018,B,A,D,A,C,B,D,A,C,C,...,0,B,D,A,B,A,A,B,0,D
N00000019,B,A,D,D,C,B,D,C,C,C,...,C,B,D,A,0,A,A,B,D,D
N00000020,B,0,D,D,C,B,D,A,C,B,...,D,B,D,B,C,A,A,B,D,D